Pal regression: Adjust cpu model name checking for Travis cpu info
Address this issue on Travis

AssertionError: 'CPU brand: Intel(R) Xeon(R) CPU' not \
found in 'User Program Started\nLoaded Executable: \
file:Bootstrap\nLoaded Manifest: file:manifest\n\
Process ID: 00059e62a170447d\n\
Host ID: 0000000000000000\n\
Parent Process: 0x0\n\
Allocation Alignment: 4096\n\
User Address Range: 0x10000 - 0x7f98ce6ab000\n\
User Address Range OK\n\
Executable Range: 0x400000 - 0x601040\n\
Executable Range OK\nCPU num: 2\n\
CPU vendor: GenuineIntel\n\
CPU brand:            Intel(R) Xeon(R) CPU\n\
CPU family: 6\n\
CPU model: 85\n\
CPU stepping: 7\n\
CPU flags: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht\n'

Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>